In [17]:
import pandas as pd

## 提出用ファイルの確認

In [18]:
output_file_path = "./model/"
filename = "sample_submit_20251220_114756.csv.gz"
suffix = "_".join(filename.split(".")[0].split("_")[2:])

In [ ]:
df = pd.read_csv(output_file_path + filename)
df.head()

In [12]:
output_filename = f"sample_submit_{suffix}.csv"
df.to_csv(output_file_path+output_filename, index=False)

## feature_importanceの確認

In [22]:
output_file_path = "./model/"
filename = f"feature_importance_{suffix}.csv.gz"

df = pd.read_csv(output_file_path + filename)

In [14]:
df.sort_values("importance", ascending=False).head(10)

               feature_name  importance
0                 TARGET_YM   24.803699
136  CITY_TOWN_VILLAGE_NAME   23.179779
68                    POST1    6.790320
3      BUILDING_CREATE_DATE    6.297450
121         SCHOOL_ELE_NAME    1.571475
135         PREFECTURE_NAME    1.534376
70                  ADDR1_1    1.513173
11                      LON    1.457751
77                EKI_NAME1    1.320848
12                      LAT    1.262396

In [16]:
df.sort_values("importance", ascending=True).head(10)

           feature_name  importance
283  UNIT_TAG_ID_233101         0.0
268  UNIT_TAG_ID_223501         0.0
269  UNIT_TAG_ID_223601         0.0
271  UNIT_TAG_ID_230102         0.0
272  UNIT_TAG_ID_230103         0.0
273  UNIT_TAG_ID_230201         0.0
274  UNIT_TAG_ID_230202         0.0
275  UNIT_TAG_ID_230203         0.0
277  UNIT_TAG_ID_230401         0.0
278  UNIT_TAG_ID_230501         0.0

In [26]:
df[df["feature_name"].isin(["walk_distance1", "walk_distance2", "convenience_distance", "drugstore_distance", "money_kyoueki", "snapshot_land_area"])]

Empty DataFrame
Columns: [feature_name, importance]
Index: []

In [ ]:
# モデルに寄与しない変数一覧
useless_variables = df[df["importance"] <= 0]["feature_name"].to_list()

In [ ]:
useless_variables

['BUILDING_ID',
 'BUILDING_STATUS',
 'HOMES_BUILDING_NAME',
 'FULL_ADDRESS',
 'BUILDING_AREA',
 'LAND_ROAD_COND',
 'UNIT_ID',
 'ROOM_FLOOR',
 'BALCONY_AREA',
 'ROOM_COUNT',
 'REFORM_ETC',
 'BUKKEN_ID',
 'SNAPSHOT_MODIFY_DATE',
 'BUKKEN_TYPE',
 'ADDR2_NAME',
 'ADDR3_NAME',
 'TRAFFIC_CAR',
 'LAND_SHIDOU_B',
 'MONEY_RIMAWARI_NOW',
 'MONEY_SHUUZENKIKIN',
 'USABLE_STATUS',
 'HOSPITAL_DISTANCE',
 'BUILDING_TAG_ID_110101',
 'BUILDING_TAG_ID_110102',
 'BUILDING_TAG_ID_113501',
 'BUILDING_TAG_ID_210101',
 'BUILDING_TAG_ID_210102',
 'BUILDING_TAG_ID_210199',
 'BUILDING_TAG_ID_210201',
 'BUILDING_TAG_ID_210299',
 'BUILDING_TAG_ID_210301',
 'BUILDING_TAG_ID_210302',
 'BUILDING_TAG_ID_210303',
 'BUILDING_TAG_ID_210399',
 'BUILDING_TAG_ID_210401',
 'BUILDING_TAG_ID_294201',
 'BUILDING_TAG_ID_295101',
 'BUILDING_TAG_ID_295401',
 'BUILDING_TAG_ID_295501',
 'BUILDING_TAG_ID_310101',
 'BUILDING_TAG_ID_310301',
 'BUILDING_TAG_ID_313101',
 'BUILDING_TAG_ID_320101',
 'BUILDING_TAG_ID_320201',
 'BUILDING_TAG_ID_320301',
 'BUILDING_TAG_ID_320501',
 'BUILDING_TAG_ID_320801',
 'BUILDING_TAG_ID_321001',
 'BUILDING_TAG_ID_323401',
 'BUILDING_TAG_ID_323601',
 'BUILDING_TAG_ID_330101',
 'BUILDING_TAG_ID_330201',
 'BUILDING_TAG_ID_330301',
 'BUILDING_TAG_ID_330401',
 'BUILDING_TAG_ID_330501',
 'BUILDING_TAG_ID_330601',
 'BUILDING_TAG_ID_331001',
 'BUILDING_TAG_ID_333601',
 'BUILDING_TAG_ID_333801',
 'BUILDING_TAG_ID_334101',
 'BUILDING_TAG_ID_334201',
 'BUILDING_TAG_ID_334301',
 'BUILDING_TAG_ID_334501',
 'BUILDING_TAG_ID_335101',
 'BUILDING_TAG_ID_335201',
 'BUILDING_TAG_ID_335401',
 'BUILDING_TAG_ID_335701',
 'BUILDING_TAG_ID_336501',
 'BUILDING_TAG_ID_336601',
 'BUILDING_TAG_ID_340301',
 'BUILDING_TAG_ID_343201',
 'BUILDING_TAG_ID_343301',
 'BUILDING_TAG_ID_343401',
 'BUILDING_TAG_ID_343601',
 'BUILDING_TAG_ID_393101',
 'BUILDING_TAG_ID_393201',
 'BUILDING_TAG_ID_410101',
 'BUILDING_TAG_ID_410201',
 'BUILDING_TAG_ID_420101',
 'BUILDING_TAG_ID_423103',
 'BUILDING_TAG_ID_423201',
 'BUILDING_TAG_ID_423301',
 'BUILDING_TAG_ID_423401',
 'BUILDING_TAG_ID_423501',
 'BUILDING_TAG_ID_433201',
 'BUILDING_TAG_ID_433301',
 'BUILDING_TAG_ID_713901',
 'BUILDING_TAG_ID_713902',
 'BUILDING_TAG_ID_713903',
 'BUILDING_TAG_ID_714001',
 'BUILDING_TAG_ID_714002',
 'BUILDING_TAG_ID_714101',
 'BUILDING_TAG_ID_714102',
 'BUILDING_TAG_ID_714103',
 'BUILDING_TAG_ID_714201',
 'BUILDING_TAG_ID_714202',
 'BUILDING_TAG_ID_714203',
 'BUILDING_TAG_ID_714301',
 'BUILDING_TAG_ID_714302',
 'BUILDING_TAG_ID_714303',
 'BUILDING_TAG_ID_NAN',
 'UNIT_TAG_ID_110201',
 'UNIT_TAG_ID_110202',
 'UNIT_TAG_ID_110301',
 'UNIT_TAG_ID_110503',
 'UNIT_TAG_ID_110601',
 'UNIT_TAG_ID_110603',
 'UNIT_TAG_ID_110901',
 'UNIT_TAG_ID_110902',
 'UNIT_TAG_ID_110903',
 'UNIT_TAG_ID_113401',
 'UNIT_TAG_ID_113402',
 'UNIT_TAG_ID_210101',
 'UNIT_TAG_ID_210102',
 'UNIT_TAG_ID_210199',
 'UNIT_TAG_ID_210202',
 'UNIT_TAG_ID_210299',
 'UNIT_TAG_ID_210302',
 'UNIT_TAG_ID_210303',
 'UNIT_TAG_ID_210399',
 'UNIT_TAG_ID_210401',
 'UNIT_TAG_ID_220102',
 'UNIT_TAG_ID_220103',
 'UNIT_TAG_ID_220201',
 'UNIT_TAG_ID_220203',
 'UNIT_TAG_ID_220301',
 'UNIT_TAG_ID_220401',
 'UNIT_TAG_ID_220501',
 'UNIT_TAG_ID_220701',
 'UNIT_TAG_ID_220801',
 'UNIT_TAG_ID_220901',
 'UNIT_TAG_ID_220902',
 'UNIT_TAG_ID_223201',
 'UNIT_TAG_ID_223401',
 'UNIT_TAG_ID_223501',
 'UNIT_TAG_ID_223601',
 'UNIT_TAG_ID_230102',
 'UNIT_TAG_ID_230103',
 'UNIT_TAG_ID_230201',
 'UNIT_TAG_ID_230202',
 'UNIT_TAG_ID_230203',
 'UNIT_TAG_ID_230401',
 'UNIT_TAG_ID_230501',
 'UNIT_TAG_ID_230601',
 'UNIT_TAG_ID_230901',
 'UNIT_TAG_ID_233101',
 'UNIT_TAG_ID_233201',
 'UNIT_TAG_ID_240101',
 'UNIT_TAG_ID_240102',
 'UNIT_TAG_ID_240103',
 'UNIT_TAG_ID_240104',
 'UNIT_TAG_ID_240201',
 'UNIT_TAG_ID_250101',
 'UNIT_TAG_ID_250201',
 'UNIT_TAG_ID_250301',
 'UNIT_TAG_ID_253201',
 'UNIT_TAG_ID_253301',
 'UNIT_TAG_ID_253401',
 'UNIT_TAG_ID_253601',
 'UNIT_TAG_ID_260101',
 'UNIT_TAG_ID_260201',
 'UNIT_TAG_ID_260401',
 'UNIT_TAG_ID_260501',
 'UNIT_TAG_ID_260502',
 'UNIT_TAG_ID_260503',
 'UNIT_TAG_ID_263101',
 'UNIT_TAG_ID_263201',
 'UNIT_TAG_ID_283201',
 'UNIT_TAG_ID_283401',
 'UNIT_TAG_ID_290101',
 'UNIT_TAG_ID_290201',
 'UNIT_TAG_ID_290401',
 'UNIT_TAG_ID_290501',
 'UNIT_TAG_ID_290601',
 'UNIT_TAG_ID_290701',
 'UNIT_TAG_ID_290801',
 'UNIT_TAG_ID_290901',
 'UNIT_TAG_ID_290902',
 'UNIT_TAG_ID_293101',
 'UNIT_TAG_ID_293301',
 'UNIT_TAG_ID_293401',
 'UNIT_TAG_ID_293501',
 'UNIT_TAG_ID_293601',
 'UNIT_TAG_ID_293801',
 'UNIT_TAG_ID_294001',
 'UNIT_TAG_ID_294101',
 'UNIT_TAG_ID_294301',
 'UNIT_TAG_ID_310101',
 'UNIT_TAG_ID_310201',
 'UNIT_TAG_ID_310501',
 'UNIT_TAG_ID_320101',
 'UNIT_TAG_ID_320401',
 'UNIT_TAG_ID_320501',
 'UNIT_TAG_ID_321101',
 'UNIT_TAG_ID_330101',
 'UNIT_TAG_ID_330501',
 'UNIT_TAG_ID_330701',
 'UNIT_TAG_ID_331001',
 'UNIT_TAG_ID_340101',
 'UNIT_TAG_ID_340102',
 'UNIT_TAG_ID_340201',
 'UNIT_TAG_ID_340501',
 'UNIT_TAG_ID_NAN',
 'REFORM_INTERIOR_',
 'REFORM_INTERIOR_1',
 'REFORM_INTERIOR_3',
 'REFORM_INTERIOR_4',
 'REFORM_INTERIOR_6',
 'REFORM_EXTERIOR_',
 'REFORM_EXTERIOR_2',
 'REFORM_EXTERIOR_NAN',
 'REFORM_WET_AREA_1',
 'REFORM_WET_AREA_2',
 'REFORM_WET_AREA_3',
 'REFORM_WET_AREA_4',
 'REFORM_WET_AREA_5',
 'REFORM_WET_AREA_6',
 'REFORM_WET_AREA_NAN',
 'STATUSES_110102',
 'STATUSES_110201',
 'STATUSES_110302',
 'STATUSES_110401',
 'STATUSES_110402',
 'STATUSES_110501',
 'STATUSES_110503',
 'STATUSES_110601',
 'STATUSES_110602',
 'STATUSES_110603',
 'STATUSES_110701',
 'STATUSES_110702',
 'STATUSES_110801',
 'STATUSES_110802',
 'STATUSES_110901',
 'STATUSES_110902',
 'STATUSES_110903',
 'STATUSES_111001',
 'STATUSES_111002',
 'STATUSES_113501',
 'STATUSES_120501',
 'STATUSES_120601',
 'STATUSES_120801',
 'STATUSES_123201',
 'STATUSES_193501',
 'STATUSES_210102',
 'STATUSES_210199',
 'STATUSES_210201',
 'STATUSES_210202',
 'STATUSES_210299',
 'STATUSES_210301',
 'STATUSES_210302',
 'STATUSES_210303',
 'STATUSES_210399',
 'STATUSES_220101',
 'STATUSES_220102',
 'STATUSES_220103',
 'STATUSES_220201',
 'STATUSES_220202',
 'STATUSES_220301',
 'STATUSES_220401',
 'STATUSES_220601',
 'STATUSES_220701',
 'STATUSES_220801',
 'STATUSES_220901',
 'STATUSES_223101',
 'STATUSES_223201',
 'STATUSES_223401',
 'STATUSES_223501',
 'STATUSES_223601',
 'STATUSES_230101',
 'STATUSES_230102',
 'STATUSES_230201',
 'STATUSES_230202',
 'STATUSES_230401',
 'STATUSES_230501',
 'STATUSES_230601',
 'STATUSES_230701',
 'STATUSES_230801',
 'STATUSES_230901',
 'STATUSES_233101',
 'STATUSES_240102',
 'STATUSES_240103',
 'STATUSES_250101',
 'STATUSES_250201',
 'STATUSES_250301',
 'STATUSES_253301',
 'STATUSES_253401',
 'STATUSES_253501',
 'STATUSES_253601',
 'STATUSES_253701',
 'STATUSES_260101',
 'STATUSES_260201',
 'STATUSES_260401',
 'STATUSES_260501',
 'STATUSES_260503',
 'STATUSES_263101',
 'STATUSES_263201',
 'STATUSES_283401',
 'STATUSES_290101',
 'STATUSES_290201',
 'STATUSES_290301',
 'STATUSES_290601',
 'STATUSES_290701',
 'STATUSES_290801',
 'STATUSES_290901',
 'STATUSES_290902',
 'STATUSES_293301',
 'STATUSES_293601',
 'STATUSES_293801',
 'STATUSES_294201',
 'STATUSES_294301',
 'STATUSES_310101',
 'STATUSES_310201',
 'STATUSES_310501',
 'STATUSES_320101',
 'STATUSES_320401',
 'STATUSES_320501',
 'STATUSES_321001',
 'STATUSES_321101',
 'STATUSES_330101',
 'STATUSES_330501',
 'STATUSES_330601',
 'STATUSES_330701',
 'STATUSES_330801',
 'STATUSES_331001',
 'STATUSES_334101',
 'STATUSES_334201',
 'STATUSES_334801',
 'STATUSES_335001',
 'STATUSES_335101',
 'STATUSES_335201',
 'STATUSES_335301',
 'STATUSES_335401',
 'STATUSES_335501',
 'STATUSES_335601',
 'STATUSES_335701',
 'STATUSES_335901',
 'STATUSES_335902',
 'STATUSES_336001',
 'STATUSES_336201',
 'STATUSES_336301',
 'STATUSES_336401',
 'STATUSES_336501',
 'STATUSES_340101',
 'STATUSES_340201',
 'STATUSES_340301',
 'STATUSES_340401',
 'STATUSES_350201',
 'STATUSES_NAN']

In [19]:
import gzip
import pickle


output_file_path = "./model/"
filename = f"model_{suffix}.pkl.gz"

with gzip.open(f"{output_file_path}/{filename}", "rb") as f:
    model = pickle.load(f)

In [ ]:
 # ツリーの確認
# model.save_model(f"{output_file_path}/model_{suffix}.json", format="json")

In [27]:
# データの読み込み
ROOT_DIR = "./dataset/"

train_df = pd.read_parquet(f"{ROOT_DIR}/processed_train.parquet")
# test_df = pd.read_parquet(f"{ROOT_DIR}/test.parquet")

In [28]:
feature_df = model.feature_importances_feature_importance = pd.DataFrame(
    {
        'feature_name': train_df.columns,
        'importance': model.get_feature_importance()
    }
)

In [ ]:
feature_df.sort_values("importance", ascending=False).head(20)

               feature_name  importance
0                 target_ym   24.803699
136  city_town_village_name   23.179779
68                    post1    6.790320
3      building_create_date    6.297450
121         school_ele_name    1.571475
135         prefecture_name    1.534376
70                  addr1_1    1.513173
11                      lon    1.457751
77                eki_name1    1.320848
12                      lat    1.262396
30              land_kenpei    0.999775
63           timelimit_date    0.867957
71                  addr1_2    0.851253
76              rosen_name1    0.806928
14         total_floor_area    0.798932

In [29]:
feature_df[feature_df["feature_name"].isin(["walk_distance1", "walk_distance2", "convenience_distance", "drugstore_distance", "money_kyoueki", "snapshot_land_area"])]

             feature_name  importance
80         walk_distance1    0.101423
85         walk_distance2    0.207650
88     snapshot_land_area    0.139726
101         money_kyoueki    0.333208
125  convenience_distance    0.286919
129    drugstore_distance    0.264172

In [32]:
train_df["school_ele_name"].head()

0      桑部小学校
1    大山田南小学校
2    大山田南小学校
3      八幡小学校
4      八幡小学校
Name: school_ele_name, dtype: large_string[pyarrow]